### ISSUE TITLE
 ICAPTester exception 

### ISSUE THREAD

**Issue by DarioLondon** [Baekalfen/ICAP-avscan#13]
I run the ICAPTester on my server but it thrrows an exception 
Unhandled Exception: ICAPNameSpace.ICAP+ICAPException: Error in getHeader() method
   at ICAPNameSpace.ICAP.getHeader(String terminator) in C:\Users\Dario\Desktop\ICAP-avscan-master\C-Sharp\ICAP\ICAP.cs:line 271
   at ICAPNameSpace.ICAP.getOptions() in C:\Users\Dario\Desktop\ICAP-avscan-master\C-Sharp\ICAP\ICAP.cs:line 234
   at ICAPNameSpace.ICAP..ctor(String serverIP, Int32 port, String icapService, Int32 previewSize) in C:\Users\Dario\Desktop\ICAP-avscan-master\C-Sharp\ICAP\ICAP.cs:line 68
   at ConsoleApplication1.Program.Main(String[] args) in C:\Users\Dario\Desktop\ICAP-avscan-master\C-Sharp\ICAPTester\Program.cs:line 17

**Comment by Baekalfen** [comment]
Did you run from a fresh copy of the code? To me, line 271 (where the exception occurred) is a comment.

**Comment by DarioLondon** [comment]
@Baekalfen  yes fresh copy of the code. On the server I have installed and configured Sophos Sav Dynamic Interface .

**Comment by DarioLondon** [comment]
@Baekalfen close this one , Configuration errors . Do you think will be possible using memorystream instead of filestream ? I dont want to save a file on the disk i just want to scan it from memory .

**Comment by Baekalfen** [comment]
Good you solved the issue! It is definitely possible to keep the file in memory instead of on the disc. You could change the first line of `scanFile` to use any other stream if you would like.
